### ISSUE TITLE
Create initial microservice skeleton code

### ISSUE THREAD

**Issue by hardy30894** [nyu-wishlist-squad/wishlists#5]
**As a** Developer 
 **I need** a microservice skeleton code 
 **So that** all the members on the team can have a standard starter code to start adding features  
   
 ### Details and Assumptions
 * The code will be in Python and Flask.
 * It should have code for CRUD operations.
 * It should have all the software dependencies in the `requirements.txt` file.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the initial microservice skeleton code GitHub repository
 When I issue a `git clone` on the repository
 Then I should get a copy of a Flask application with the initial microservice skeleton code
When Docker is running on the system and I run `code .` inside the project folder
Then the project should install all the software prerequisites for the project and start the container with the development environment setup
When I run `flask run -h 0.0.0.0 -p 8000` on the `bash` terminal
Then it should run the service on `http://localhost:8000/`
 ```

**Comment by myan9** [comment]
Not needed as we have project template
